### ISSUE TITLE
Add me as a member.

### ISSUE THREAD

**Issue by dunmatt** [rust-embedded-community/meta#13]
Over in https://github.com/newAM/w5500-hl-rs/issues/14 eldruin suggested that I join this org and we transfer no-std-net here.  I think that makes a lot of sense, if you agree, let's do it.

**Comment by eldruin** [comment]
I would be glad to :) let's see if others agree as well.

**Comment by eldruin** [comment]
It's been 11 days so @dunmatt, could you go ahead with opening a PR adding yourself to the README for approval?
