### ISSUE TITLE
tcs3400

### ISSUE THREAD

**Issue by andresv** [rust-embedded-community/meta#16]
Hi, I would like to share https://crates.io/crates/tcs3400 ownership.

**Comment by eldruin** [comment]
Alright. Since only org members can transfer repos in, please transfer the repo to me and I will transfer it to this org and grant you privileges.
Then same thing for crates.io. On the command line would be `cargo owner --add eldruin` and then I will add the r-e-c.

**Comment by eldruin** [comment]
Thanks! I did the rest and the driver is now available at [tcs3400-rs](https://github.com/rust-embedded-community/tcs3400-rs).
Closing.
