### ISSUE TITLE
motor driver crate: tb6612fng-rs

### ISSUE THREAD

**Issue by rursprung** [rust-embedded-community/meta#18]
i'd like to offer/nominate the [tb6612fng-rs](https://github.com/rursprung/tb6612fng-rs/) crate created by me (with contributions from @ripytide) to be migrated here as i don't even have the matching hardware anymore (and while i can still access it for the time being this will change eventually). i do not expect the crate to undergo a lot more changes in the future (we're currently iterating on it a bit to clean up the API as part of the e-h 1.0 migration, but after that it should "just work").

the crate provides a simple rust API to interact with the [motor driver of the same name](https://www.sparkfun.com/datasheets/Robotics/TB6612FNG.pdf) and is based on `embedded-hal` 1.0. the repo comes with CI, documentation and a working example (based on an STM32F4).

the README talks about you forking the repo - is it also possible for you to move the whole repo into the org so that the PRs & issues aren't lost (mainly for historization of the conversations)?

**Comment by eldruin** [comment]
Sure, that seems appropriate.
Would you also like to join this org as well or transfer the repo and I will grant you privileges on it?

**Comment by rursprung** [comment]
thanks!

> Would you also like to join this org as well and transfer the repo yourself or only transfer the repo and I will grant you privileges on it?

thanks for the offer of joining the org. having had a look at the other repos in the org i do not currently feel comfortable (or have the time) to contribute to / help maintain them. thus transfering the repo & being granted on it would be the better option (for now).
shall i grant you on the repo so you can transfer it? or do you need to temporarily add me to the org so that i can transfer it?

**Comment by eldruin** [comment]
Thanks! The repository is now available [here](https://github.com/rust-embedded-community/tb6612fng-rs)
