### ISSUE TITLE
provide org-level README

### ISSUE THREAD

**Issue by rursprung** [rust-embedded-community/meta#19]
it'd be nice if you could create a `.github` repository in the org and add a README for the organisation. see the [GH documentation](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile) for further details.

i'd suggest to rename the `meta` repo to `.github` and symlinking `README.md` to `profile/README.md` (presuming symlinks work for this? haven't tested it).

this would help visitors to immediately find the information - i had also missed the `meta` repo.

**Comment by eldruin** [comment]
Thanks!
I have created a profile now with a shortened description since the one here is too long.
Feel free to propose improvements.
