### ISSUE TITLE
Need a Github Team to own things on crates.io

### ISSUE THREAD

**Issue by thejpster** [rust-embedded-community/meta#2]
I'm still the owner of pc-keyboard (and other things) on crates.io, and that's a low bus number. I can add a "Github Team" as the owner of my crates, but someone on here needs to create a team first.

Paging @jamesmunns @eldruin @disasm

**Comment by eldruin** [comment]
Sure, now the big question: which name? :)

**Comment by eldruin** [comment]
ah, "all" is probably fine since we do not have subteams. I'll create one.

**Comment by thejpster** [comment]
On a related note, could I get an invite back into this org? I don't have the bandwidth for rust-embedded, but I do find the odd spare hour and the ability to merge some PRs here would be useful.

**Comment by eldruin** [comment]
You are part of this org with your other account @jonathanpallant. I invited that account to the "all" team as well. I do not see how to add new members to the org. Maybe I do not have the rights?

**Comment by thejpster** [comment]
Ah, that's my work account and I don't have access to that on my personal laptop - I use @thejpster for non work things.

**Comment by thejpster** [comment]
Nothing in https://github.com/orgs/rust-embedded-community/people?

**Comment by thejpster** [comment]
![image](https://user-images.githubusercontent.com/959887/87875318-731acd80-c9c8-11ea-8813-c42da9778b1c.png)

**Comment by eldruin** [comment]
Yes I am missing the rights. I am listed there as Member, but @Disasm and @jamesmunns are listed as owners. Maybe they can help?

**Comment by thejpster** [comment]
Sorted. Thanks!
