### ISSUE TITLE
move adafruit-bluefruit-protocol-rs to r-e-c

### ISSUE THREAD

**Issue by rursprung** [rust-embedded-community/meta#21]
i'd like to offer/nominate the [adafruit-bluefruit-protocol-rs](https://github.com/rursprung/adafruit-bluefruit-protocol-rs/) crate created by me to be migrated here as i don't even have the matching hardware anymore (and while i can still access it for the time being this will change eventually). i do not expect the crate to undergo a lot more changes in the future, beyond eventually releasing a v1.0 once its dependencies have also reached v1.0 (see the tracking issue: https://github.com/rursprung/adafruit-bluefruit-protocol-rs/issues/25).

the crate implements the [Adafruit Bluefruit LE Connect controller protocol](https://learn.adafruit.com/bluefruit-le-connect/controller) which is e.g. used by the [Adafruit Bluefruit LE UART Friend](https://learn.adafruit.com/introducing-the-adafruit-bluefruit-le-uart-friend).

at this point it does not offer any direct hardware interaction and instead expects to receive a string.

**Comment by eldruin** [comment]
Sounds like a good match for this org!

**Comment by eldruin** [comment]
Thanks! The transfer has now been completed.
