### ISSUE TITLE
Add detailed instructions for transferring crate ownership to R-E-C

### ISSUE THREAD

**Issue by ryan-summers** [rust-embedded-community/meta#23]
We should add instructions to let users know how they can transfer projects to this organization. Specifically:
1. How to transfer the repo to the R-E-C org
2. How to add the appropriate crates.io owners to the existing crate
3. How to get re-added to the R-E-C if the owner wants to retain ownership/control of the crate as well

We're going over this now with the transfer of `usbd-midi` and I realized we don't really have this documented anywhere to point to easily.

**Comment by eldruin** [comment]
Good point! I would say we could place this in a TRANSFER.md (or whatever better name) file here.
