### ISSUE TITLE
Transfer `riscv-atomic-emulation-trap` & `xtensa-atomic-emulation-trap`

### ISSUE THREAD

**Issue by MabezDev** [rust-embedded-community/meta#25]
We had been using [riscv-atomic-emulation-trap](https://github.com/esp-rs/riscv-atomic-emulation-trap) & [xtensa-atomic-emulation-trap](https://github.com/esp-rs/xtensa-atomic-emulation-trap) in esp-hal for a couple of years, but we've switched to `portable-atomic` everywhere, now that LLVM is a bit smarter. We were planning on archiving these repos, but wondered if they would be better served here. I recall a couple of people using at the very least the `riscv-atomic-emulation-trap` in some projects.

**Comment by eldruin** [comment]
Good question. If they are completely unnecessary from now on, maybe archiving them in the current org is more appropriate. Also, there are multiple maintainers there as well that can unarchive the repo if actually necessary. A potential transfer here can be triggered then.

**Comment by MabezDev** [comment]
cc: @romancardenas sorry for the ping, I forget if you are using the riscv one or not?

**Comment by romancardenas** [comment]
Hi there! I also moved to `portable-atomic`, so I am not currently using this crate. I was planning to adapt `riscv-rt` to be compatible with `riscv-atomic-emulation-trap`, but this would lead to breaking changes that might be unnecessary if other alternatives are better/more common.

**Comment by MabezDev** [comment]
Thanks, in which case I will close this and archive both the repos.
