### ISSUE TITLE
Join request

### ISSUE THREAD

**Issue by sourcebox** [rust-embedded-community/meta#26]
As discussed on Matrix, I've been transferred over the maintainership of usbd-midi and want to pass it over to this group.

**Comment by eldruin** [comment]
Sounds good to me. Please have a look [here](https://github.com/rust-embedded-community/meta/blob/master/TRANSFER.md) and then either open a PR to join this org or transfer the repo to me.

**Comment by sourcebox** [comment]
Thanks!
