### ISSUE TITLE
Transfer SSD1306, SSD1331 and SH1106 drivers to r-e-c

### ISSUE THREAD

**Issue by jamwaffles** [rust-embedded-community/meta#28]
As per [the instructions](https://github.com/rust-embedded-community/meta/blob/master/TRANSFER.md#transfer-process-without-joining), would someone be so kind as to nominate themselves or another username so I can transfer https://github.com/jamwaffles/ssd1306, https://github.com/jamwaffles/ssd1331 and https://github.com/jamwaffles/sh1106 to r-e-c please?

**Comment by eldruin** [comment]
You can transfer them to me. Thank you for all your work! I have actually used the ssd1306 crate many times :)

**Comment by jamwaffles** [comment]
I'm glad my code has been useful :)

Heh... this is a fun edgecase:

![image](https://github.com/rust-embedded-community/meta/assets/800791/28862639-5e1f-4090-a882-70c7afd262a5)

![image](https://github.com/rust-embedded-community/meta/assets/800791/739d9625-c971-4d54-8017-2baf71c6096f)

Would it be best to delete your forks or do they have additional changes in them?

**Comment by rfuest** [comment]
If you like I could also help with maintaining the crates. I don't have any SSD1331 displays, but the e-g test board we designed with a SSD1306 display and a SH1106 display is always ready to test reported issues.

How about creating an org for the embedded display drivers to share the maintenance burden? Maybe @almindor would also be interested in adding the `mipidsi` crate to that org to have the most popular e-g display drivers in a common place? This could also facilitate code reuse between the different drivers, like what was planned with the [`display-driver-hal`](https://github.com/embedded-graphics/display-driver-hal) and [`packed-display-buffer`](https://github.com/embedded-graphics/packed-display-buffer) crates.

The `display-interface` crate also doesn't seem to be very actively maintained at the moment and could also live in that org, if the owner agrees.

**Comment by eldruin** [comment]
> Would it be best to delete your forks or do they have additional changes in them?

I had not encountered that yet either. I just submitted changes a long time ago. I have removed my forks now.

Regarding an additional org please feel free to choose as you will. I would only say that anybody is welcome to join this org and we are open to accepting more crates as well and help maintain them. At the moment we are 11 members (not all public) and 9 outside collaborators so crates probably have a good chance here.
Either way, you have my encouragement.

**Comment by jamwaffles** [comment]
> I had not encountered that yet either. I just submitted changes a long time ago. I have removed my forks now.

Thanks. I've started the transfer of those two crates.

> How about creating an org for the embedded display drivers to share the maintenance burden?

Interesting idea but I no longer have a horse in this race so I'll let others decide what to do. I'm opening up possibilities by transferring these crates into r-e-c but beyond that, go wild :)

**Comment by eldruin** [comment]
Alright. I have completed the transfer to this org, then.
@rfuest what I said still stands. Just let us know what you want to do.

**Comment by almindor** [comment]
> If you like I could also help with maintaining the crates. I don't have any SSD1331 displays, but the e-g test board we designed with a SSD1306 display and a SH1106 display is always ready to test reported issues.
> 
> How about creating an org for the embedded display drivers to share the maintenance burden? Maybe @almindor would also be interested in adding the `mipidsi` crate to that org to have the most popular e-g display drivers in a common place? This could also facilitate code reuse between the different drivers, like what was planned with the [`display-driver-hal`](https://github.com/embedded-graphics/display-driver-hal) and [`packed-display-buffer`](https://github.com/embedded-graphics/packed-display-buffer) crates.
> 
> The `display-interface` crate also doesn't seem to be very actively maintained at the moment and could also live in that org, if the owner agrees.

I'm not opposed to having a graphics org. Right now it seems it's just me in maintenance mode and @rfuest so it'd be great if we could get more people interested and widen the approval pool.

**Comment by jamwaffles** [comment]
These all look to be in e-g-c now so I'll close this issue. Thanks for moving them @eldruin!
