### ISSUE TITLE
st7567s driver transfer

### ISSUE THREAD

**Issue by kattouf** [rust-embedded-community/meta#29]
Hello!

I’d like to transfer ownership of my [ST7567S library](https://github.com/kattouf/st7567s?tab=readme-ov-file) to the community. I originally created it to meet the needs of one of my personal projects, but I’ve since moved away from embedded programming. I’d be happy to see the library continue to be useful even without my direct involvement.

**Comment by eldruin** [comment]
Hi @kattouf! That sounds fine to me. Could you have a look [here](https://github.com/rust-embedded-community/meta/blob/master/TRANSFER.md) and let us know how you want to do the transfer?

**Comment by kattouf** [comment]
I'd like to go through the Transfer Process (Without Joining) flow and have already sent you an invite to the GitHub repo and added you as a cargo owner, according to [the documentation](https://github.com/rust-embedded-community/meta/blob/master/TRANSFER.md). Let me know if there's anything else I need to do.

**Comment by eldruin** [comment]
Thank you, I have completed the transfer. You are still granted write privileges, though.
Thank you for all your work on this library!
