### ISSUE TITLE
Community mission

### ISSUE THREAD

**Issue by eldruin** [rust-embedded-community/meta#7]
Should this community stay as a "homeless care" for crates or rather transition into something more of a non-blessed but still prominent rust-embedded?
c.f. #4 #5 #6

Personally I would welcome making more out of this.
What do you think @rust-embedded-community/all ?

PS: @rust-embedded-community/all: I am the only watcher of this repository. You probably missed doing that since it was added later.

**Comment by thejpster** [comment]
I'm generally quiet as I have all my notifications disabled for 12 months (until May 2021) but I'm keeping an eye on this seem as I was one of those who came up with the idea.

To me the Rust Embedded Community is not just a home of last resort - it is a place for developers to put crates when they feel that their personal servers / GitHub orgs / bitbucket orgs / gitlab orgs / etc, give them a bus number that is unacceptably low. To use a slightly dodgy analogy, moving a crate here doesn't change its parentage, but it does perhaps give a crate lots of aunts and uncles (or "friends of the family" or "God Parents" if that works better for you) who can keep an eye on that crate and ensure it is never abandoned.

**Comment by eldruin** [comment]
(@ryankurte I would be very glad to have you as part of this org!)
