### ISSUE TITLE
Take ownership of serde-json-core

### ISSUE THREAD

**Issue by MathiasKoch** [rust-embedded-community/meta#8]
As mentioned in the issue opened in `serde-json-core`, I think this would make a perfect fit for the rust-embedded-community organization, seeing as it currently seems to have stalled the maintenance a bit, and it is in my optic a core crate for lots of embedded application areas.

Related issue in serde-json-core: https://github.com/japaric/serde-json-core/issues/37

**Comment by eldruin** [comment]
This has been done. Thanks!
